require 'nokogiri'
require 'open-uri'
require 'colorize'

require_relative '../lib/upcoming_movies_in_the_park/version'
require_relative '../lib/upcoming_movies_in_the_park/super'
require_relative '../lib/upcoming_movies_in_the_park/cli'
require_relative '../lib/upcoming_movies_in_the_park/showing'
require_relative '../lib/upcoming_movies_in_the_park/park'
require_relative '../lib/upcoming_movies_in_the_park/gate'
require_relative '../lib/upcoming_movies_in_the_park/scraper'